### ISSUE TITLE
Firebase database related query

### ISSUE THREAD

**Issue by Shaliniyadav8130** [onkarnp/Bloodoor#1]
Hello sir, I am working on a mini project which is related to Blood donation. But still I have not proper knowledge of Firebase database and application. Please provide me your firebase database password So that I can use it. Please help me I assure you that I will not misuse of database. There is no mail available on your profile that's why I created a Issue. Please Sir help me.

**Comment by onkarnp** [comment]
Hi @Shaliniyadav8130 , Kindly check your mail for the query you raised.
